<?PHP
SESSION_START();
INCLUDE $_SERVER['DOCUMENT_ROOT'] . '/api/config.php';

// 1. ANCLAR EL PHPSESSION DE FIREBASE A LA SESIÓN DE PHP
IF (ISSET($_GET['phpsession'])) {
    $_SESSION['PHPSESS_MOTOR'] = $_GET['phpsession'];
    
    // RECONSTRUIR URL PARA OCULTAR EL TOKEN
    $PARAMS = $_GET;
    UNSET($PARAMS['phpsession']);
    $NUEVA_URL = $_SERVER['PHP_SELF'] . '?' . HTTP_BUILD_QUERY($PARAMS);
    
    HEADER("LOCATION: $NUEVA_URL");
    EXIT();
}

// 2. VERIFICAR QUE EXISTE SESIÓN ACTIVA
IF (!ISSET($_SESSION['PHPSESS_MOTOR'])) {
    HEADER("LOCATION: /login.php");
    EXIT();
}

// 3. GENERAR TOKEN VOLÁTIL PARA LOS IFRAMES
$TOKEN_VOLATIL = MD5(UNIQID(RAND(), TRUE));
$_SESSION['TOKEN_IFRAME'] = $TOKEN_VOLATIL;

// ESTRUCTURA HTML TRANSITIONAL
ECHO "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 TRANSITIONAL//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<HTML>
<HEAD>
    <TITLE>PANEL EMPRESARIO</TITLE>
    <META HTTP-EQUIV='CONTENT-TYPE' CONTENT='TEXT/HTML; CHARSET=UTF-8'>
    <STYLE TYPE='TEXT/CSS'>
        BODY, HTML { MARGIN: 0; PADDING: 0; HEIGHT: 100%; OVERFLOW: HIDDEN; FONT-FAMILY: VERDANA; }
        .MASTER-CONTAINER { DISPLAY: FLEX; WIDTH: 100%; HEIGHT: 100%; }
        #SIDEBAR-FRAME { WIDTH: 250PX; HEIGHT: 100%; BORDER: NONE; BORDER-RIGHT: 1PX SOLID #000; }
        #MAIN-FRAME { FLEX-GROW: 1; HEIGHT: 100%; BORDER: NONE; }
    </STYLE>
</HEAD>
<BODY>

<DIV CLASS='MASTER-CONTAINER'>
    <IFRAME 
        ID='SIDEBAR-FRAME' 
        SRC='/sempresa/empresario/servless/sidebar.php?ALEATORIO=$TOKEN_VOLATIL' 
        NAME='SIDEBAR'>
    </IFRAME>
    
    <IFRAME 
        ID='MAIN-FRAME' 
        SRC='/sempresa/empresario/servless/contenidoPrincipal.php?ALEATORIO=$TOKEN_VOLATIL' 
        NAME='CONTENIDO'>
    </IFRAME>
</DIV>

</BODY>
</HTML>";
?>
