<?PHP
// INICIAMOS SESIÓN PARA OCULTAR EL TOKEN DE LA URL
SESSION_START();
INCLUDE $_SERVER['DOCUMENT_ROOT'] . '/api/config.php';

// 1. CAPTURA Y OCULTACIÓN DE PHPSESSION
IF (ISSET($_GET['phpsession'])) {
    $_SESSION['PHPSESS_MOTOR'] = $_GET['phpsession'];
    
    // RECONSTRUIR URL SIN PHPSESSION
    $PARAMS = $_GET;
    UNSET($PARAMS['phpsession']);
    $NUEVA_URL = $_SERVER['PHP_SELF'] . '?' . HTTP_BUILD_QUERY($PARAMS);
    
    HEADER("LOCATION: $NUEVA_URL");
    EXIT();
}

// 2. VALIDACIÓN DE SEGURIDAD
$PHPSESS_VAL = $_SESSION['PHPSESS_MOTOR'] ?? '';
IF (EMPTY($PHPSESS_VAL)) {
    DIE("ACCESO NO AUTORIZADO");
}

// 3. GENERAR ALEATORIO VOLÁTIL (CAMBIA EN CADA CARGA)
// ESTE VALOR SÓLO SERÁ VÁLIDO PARA ESTA CARGA DE PÁGINA
$TOKEN_VOLATIL = MD5(UNIQID(RAND(), TRUE));
$_SESSION['ULTIMO_ALEATORIO'] = $TOKEN_VOLATIL;

// ESTRUCTURA HTML TRANSITIONAL
ECHO "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 TRANSITIONAL//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<HTML>
<HEAD>
    <TITLE>PANEL EMPRESARIO</TITLE>
    <META HTTP-EQUIV='CONTENT-TYPE' CONTENT='TEXT/HTML; CHARSET=UTF-8'>
    <STYLE TYPE='TEXT/CSS'>
        BODY, HTML { MARGIN: 0; PADDING: 0; HEIGHT: 100%; OVERFLOW: HIDDEN; FONT-FAMILY: VERDANA; }
        .CONTENEDOR-FRAMES { DISPLAY: FLEX; WIDTH: 100%; HEIGHT: 100%; }
        #SIDEBAR { WIDTH: 250PX; HEIGHT: 100%; BORDER: NONE; BORDER-RIGHT: 1PX SOLID #CCCCCC; }
        #CONTENIDO { FLEX-GROW: 1; HEIGHT: 100%; BORDER: NONE; }
    </STYLE>
</HEAD>
<BODY>

<DIV CLASS='CONTENEDOR-FRAMES'>
    <IFRAME 
        ID='SIDEBAR' 
        SRC='/sempresa/empresario/servless/sidebar.php?ALEATORIO=$TOKEN_VOLATIL' 
        NAME='SIDEBAR'>
    </IFRAME>
    
    <IFRAME 
        ID='CONTENIDO' 
        SRC='/sempresa/empresario/servless/contenidoPrincipal.php?ALEATORIO=$TOKEN_VOLATIL' 
        NAME='CONTENIDO'>
    </IFRAME>
</DIV>

</BODY>
</HTML>";
?>
