<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <TITLE>ACCESO EMPRESARIOS</TITLE>
    <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=UTF-8">
    <STYLE TYPE="TEXT/CSS">
        BODY { FONT-FAMILY: VERDANA, GENEVA, SANS-SERIF; BACKGROUND-COLOR: #F0F0F0; TEXT-ALIGN: CENTER; }
        .CAJA { WIDTH: 350PX; MARGIN: 100PX AUTO; PADDING: 40PX; BACKGROUND: #FFFFFF; BORDER: 1PX SOLID #999999; }
        H2 { COLOR: #333333; FONT-SIZE: 18PX; MARGIN-BOTTOM: 20PX; }
        INPUT { WIDTH: 90%; PADDING: 8PX; MARGIN: 10PX 0; BORDER: 1PX SOLID #666666; FONT-FAMILY: VERDANA; }
        .BOTON { BACKGROUND-COLOR: #222222; COLOR: #FFFFFF; PADDING: 10PX; WIDTH: 95%; CURSOR: POINTER; BORDER: NONE; FONT-WEIGHT: BOLD; }
    </STYLE>
</HEAD>
<BODY>

<DIV CLASS="CAJA">
    <H2>Acceso para empresarios</H2>
    <FORM ACTION="procesar.php" METHOD="POST">
        <INPUT TYPE="TEXT" NAME="USUARIO" PLACEHOLDER="Usuario" REQUIRED>
        <BR>
        <INPUT TYPE="PASSWORD" NAME="CONTRASENA" PLACEHOLDER="Contraseña" REQUIRED>
        <BR>
        <BUTTON TYPE="SUBMIT" CLASS="BOTON">ENTRAR</BUTTON>
    </FORM>
</DIV>

</BODY>
</HTML>
