<?PHP
// CONFIGURACIÓN DE FIREBASE (OCULTA EN EL SERVIDOR)
$PROJECT_ID = "hostingimage1";
// ESTE ES EL NOMBRE DEL CAMPO QUE BUSCAMOS EN FIRESTORE
$FIELD_NAME = "contrasena";

$MENSAJE_ERROR = "";

IF ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $USUARIO_INPUT = $_POST['USUARIO'] ?? '';
    $CLAVE_INPUT = $_POST['CLAVE'] ?? '';

    IF (!EMPTY($USUARIO_INPUT) && !EMPTY($CLAVE_INPUT)) {
        // CONSULTA A LA API REST DE FIRESTORE
        $URL = "HTTPS://FIRESTORE.GOOGLEAPIS.COM/V1/PROJECTS/$PROJECT_ID/DATABASES/(DEFAULT)/DOCUMENTS/USUARIOS/" . URLENCODE($USUARIO_INPUT);
        
        $CH = CURL_INIT($URL);
        CURL_SETOPT($CH, CURLOPT_RETURNTRANSFER, TRUE);
        CURL_SETOPT($CH, CURLOPT_TIMEOUT, 10);
        CURL_SETOPT($CH, CURLOPT_SSL_VERIFYPEER, TRUE);
        
        $RESPONSE = CURL_EXEC($CH);
        $HTTP_CODE = CURL_GETINFO($CH, CURLINFO_HTTP_CODE);
        CURL_CLOSE($CH);

        IF ($HTTP_CODE == 200) {
            $DATA = JSON_DECODE($RESPONSE, TRUE);
            // ACCEDEMOS A LA ESTRUCTURA JSON DE FIRESTORE PARA OBTENER EL STRING
            $CLAVE_FIRESTORE = $DATA['FIELDS'][$FIELD_NAME]['STRINGVALUE'] ?? '';

            IF ($CLAVE_INPUT === $CLAVE_FIRESTORE) {
                // LOGIN CORRECTO - INICIAMOS SESIÓN
                SESSION_START();
                $_SESSION['EMPRESA_LOGUEADA'] = $USUARIO_INPUT;
                HEADER("LOCATION: /PANEL-CONTROL.PHP");
                EXIT;
            } ELSE {
                $MENSAJE_ERROR = "CONTRASEÑA INCORRECTA";
            }
        } ELSEIF ($HTTP_CODE == 404) {
            $MENSAJE_ERROR = "EL USUARIO NO EXISTE EN LA BASE DE DATOS";
        } ELSE {
            $MENSAJE_ERROR = "ERROR DE CONEXIÓN CON EL SERVIDOR DE DATOS";
        }
    } ELSE {
        $MENSAJE_ERROR = "TODOS LOS CAMPOS SON OBLIGATORIOS";
    }
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 TRANSITIONAL//EN" "HTTP://WWW.W3.ORG/TR/XHTML1/DTD/XHTML1-TRANSITIONAL.DTD">
<HTML XMLNS="HTTP://WWW.W3.ORG/1999/XHTML">
<HEAD>
    <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=UTF-8" />
    <TITLE>ACCESO RESTRINGIDO - EMPRESARIOS</TITLE>
    <STYLE TYPE="TEXT/CSS">
        * { MARGIN: 0; PADDING: 0; BOX-SIZING: BORDER-BOX; FONT-FAMILY: 'ROBOTO', SANS-SERIF; }
        BODY {
            HEIGHT: 100VH;
            DISPLAY: FLEX;
            ALIGN-ITEMS: CENTER;
            JUSTIFY-CONTENT: CENTER;
            BACKGROUND-IMAGE: URL('IMG/3.JPG'); /* ASEGÚRATE DE QUE ESTA RUTA EXISTE */
            BACKGROUND-COLOR: #1A1A1A; 
            BACKGROUND-POSITION: CENTER;
            BACKGROUND-REPEAT: NO-REPEAT;
            BACKGROUND-SIZE: COVER;
            COLOR: #FFF;
        }
        .CONTAINER-FORM { WIDTH: 90%; HEIGHT: 90VH; DISPLAY: FLEX; JUSTIFY-CONTENT: SPACE-AROUND; ALIGN-ITEMS: CENTER; }
        .WELCOME-BACK { DISPLAY: FLEX; ALIGN-ITEMS: CENTER; TEXT-ALIGN: CENTER; }
        .MESSAGE { PADDING: 1REM; BACKGROUND: RGBA(0,0,0,0.5); BORDER-RADIUS: 5PX; }
        .MESSAGE H2 { FONT-SIZE: 1.7REM; PADDING: 1REM 0; TEXT-TRANSFORM: UPPERCASE; }
        .FORMULARIO { WIDTH: 400PX; PADDING: 1REM; MARGIN: 2REM; BACKGROUND-COLOR: RGBA(51, 51, 51, 0.6); TEXT-ALIGN: CENTER; BORDER-RADIUS: 5PX; }
        .CREATE-ACCOUNT { PADDING: 2.7REM 0; FONT-SIZE: 1.7REM; TEXT-TRANSFORM: UPPERCASE; }
        .FORMULARIO INPUT {
            WIDTH: 70%;
            DISPLAY: BLOCK;
            MARGIN: AUTO;
            MARGIN-BOTTOM: 2REM;
            BACKGROUND-COLOR: TRANSPARENT;
            BORDER: NONE;
            BORDER-BOTTOM: WHITE THIN SOLID;
            TEXT-ALIGN: CENTER;
            OUTLINE: NONE;
            PADDING: .2REM 0;
            FONT-SIZE: .9REM;
            COLOR: WHITE;
            TEXT-TRANSFORM: UPPERCASE;
        }
        .FORMULARIO INPUT[TYPE="SUBMIT"] {
            WIDTH: 60%;
            MARGIN: AUTO;
            BORDER: SOLID THIN WHITE;
            PADDING: .7REM;
            BORDER-RADIUS: 2REM;
            BACKGROUND-COLOR: WHITE;
            FONT-WEIGHT: 600;
            MARGIN-TOP: 3REM;
            FONT-SIZE: .8REM;
            CURSOR: POINTER;
            COLOR: #222;
            TEXT-TRANSFORM: UPPERCASE;
            TRANSITION: ALL .3S EASE;
        }
        .FORMULARIO INPUT[TYPE="SUBMIT"]:HOVER { BACKGROUND-COLOR: #4A4AEE; COLOR: #FFF; BORDER-COLOR: #4A4AEE; }
        .ERROR-BOX { MARGIN-TOP: 20PX; COLOR: #FF6B6B; FONT-SIZE: 0.8REM; FONT-WEIGHT: BOLD; TEXT-TRANSFORM: UPPERCASE; }
    </STYLE>
</HEAD>
<BODY>

    <DIV CLASS="CONTAINER-FORM">
        <DIV CLASS="WELCOME-BACK">
            <DIV CLASS="MESSAGE">
                <H2>BIENVENIDO EMPRESARIO</H2>
                <P>INGRESE SUS CREDENCIALES PARA ACCEDER AL PANEL DE CONTROL.</P>
            </DIV>
        </DIV>

        <DIV CLASS="FORMULARIO">
            <FORM ACTION="" METHOD="POST">
                <H2 CLASS="CREATE-ACCOUNT">ACCEDE COMO EMPRESARIO</H2>
                
                <INPUT TYPE="TEXT" NAME="USUARIO" PLACEHOLDER="USUARIO" REQUIRED="REQUIRED" />
                <INPUT TYPE="PASSWORD" NAME="CLAVE" PLACEHOLDER="CONTRASEÑA" REQUIRED="REQUIRED" />
                
                <INPUT TYPE="SUBMIT" VALUE="INICIAR SESIÓN" />
            </FORM>

            <?PHP IF (!EMPTY($MENSAJE_ERROR)): ?>
                <DIV CLASS="ERROR-BOX">
                    <?PHP ECHO $MENSAJE_ERROR; ?>
                </DIV>
            <?PHP ENDIF; ?>
        </DIV>
    </DIV>

</BODY>
</HTML>
