<?PHP INCLUDE $_SERVER['DOCUMENT_ROOT'] . '/api/config.php'; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <TITLE>ACCESO PRIVADO</TITLE>
    <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=UTF-8">
    <STYLE TYPE="TEXT/CSS">
        BODY { FONT-FAMILY: VERDANA, GENEVA, SANS-SERIF; BACKGROUND-COLOR: #EEEEEE; TEXT-ALIGN: CENTER; MARGIN: 0; PADDING: 0; }
        .CAJA-CENTRAL { WIDTH: 450PX; MARGIN: 150PX AUTO; PADDING: 30PX; BACKGROUND: #FFFFFF; BORDER: 2PX SOLID #333333; BOX-SHADOW: 10PX 10PX 0PX #999999; }
        H1 { FONT-SIZE: 20PX; COLOR: #000000; MARGIN-BOTTOM: 25PX; TEXT-TRANSFORM: NONE; }
        .CAMPO { MARGIN-BOTTOM: 15PX; TEXT-ALIGN: LEFT; }
        LABEL { DISPLAY: BLOCK; FONT-WEIGHT: BOLD; MARGIN-BOTTOM: 5PX; FONT-SIZE: 12PX; }
        INPUT[TYPE="TEXT"], INPUT[TYPE="PASSWORD"] { WIDTH: 100%; PADDING: 8PX; BOX-SIZING: BORDER-BOX; BORDER: 1PX SOLID #000000; FONT-FAMILY: VERDANA; }
        .BOTON-ENVIO { BACKGROUND-COLOR: #000000; COLOR: #FFFFFF; PADDING: 10PX 25PX; BORDER: NONE; CURSOR: POINTER; FONT-FAMILY: VERDANA; FONT-WEIGHT: BOLD; WIDTH: 100%; MARGIN-TOP: 10PX; }
        .BOTON-ENVIO:HOVER { BACKGROUND-COLOR: #444444; }
    </STYLE>
    
    <SCRIPT SRC="HTTPS://WWW.GSTATIC.COM/FIREBASEJS/9.1.0/FIREBASE-APP-COMPAT.JS"></SCRIPT>
    <SCRIPT SRC="HTTPS://WWW.GSTATIC.COM/FIREBASEJS/9.1.0/FIREBASE-DATABASE-COMPAT.JS"></SCRIPT>
</HEAD>
<BODY>

<DIV CLASS="CAJA-CENTRAL">
    <H1>Acceso para empresarios</H1>
    <FORM ID="LOGIN-FORM">
        <DIV CLASS="CAMPO">
            <LABEL>USUARIO:</LABEL>
            <INPUT TYPE="TEXT" ID="USER_ID" NAME="USER_ID" REQUIRED>
        </DIV>
        <DIV CLASS="CAMPO">
            <LABEL>CONTRASEÑA:</LABEL>
            <INPUT TYPE="PASSWORD" ID="USER_PASS" NAME="USER_PASS" REQUIRED>
        </DIV>
        <BUTTON TYPE="SUBMIT" CLASS="BOTON-ENVIO">INICIAR SESIÓN</BUTTON>
    </FORM>
</DIV>

<SCRIPT TYPE="TEXT/JAVASCRIPT">
    // SE OBTIENEN LOS DATOS DESDE EL ARCHIVO EN /API/CONFIG.PHP
    VAR FIREBASE_DATA = <?PHP ECHO JSON_ENCODE($FIREBASE_CONFIG); ?>;

    // INICIALIZACIÓN
    FIREBASE.INITIALIZEAPP(FIREBASE_DATA);
    VAR DATABASE = FIREBASE.DATABASE();

    DOCUMENT.GETELEMENTBYID('LOGIN-FORM').ADDEVENTLISTENER('SUBMIT', FUNCTION(E) {
        E.PREVENTDEFAULT();

        VAR USUARIO_INPUT = DOCUMENT.GETELEMENTBYID('USER_ID').VALUE;
        VAR PASS_INPUT = DOCUMENT.GETELEMENTBYID('USER_PASS').VALUE;

        // CONSULTA EN EL NODO usuarios/{usuario}
        DATABASE.REF('usuarios/' + USUARIO_INPUT).ONCE('VALUE').THEN(FUNCTION(SNAPSHOT) {
            IF (SNAPSHOT.EXISTS()) {
                VAR USUARIO_DATA = SNAPSHOT.VAL();

                // VALIDACIÓN DE CONTRASEÑA (STRING)
                IF (USUARIO_DATA.contrasena === PASS_INPUT) {
                    
                    // GENERACIÓN DE NUEVO PHPSESSIONID
                    VAR NUEVA_SESION = MATH.RANDOM().TOSTRING(36).SUBSTRING(2, 15).TOUPPERCASE();
                    
                    // ACTUALIZACIÓN EN FIREBASE
                    DATABASE.REF('usuarios/' + USUARIO_INPUT).UPDATE({
                        phpsession: NUEVA_SESION
                    }).THEN(FUNCTION() {
                        
                        // GENERACIÓN DE PARÁMETROS ALEATORIOS PARA REDIRECCIÓN
                        VAR TEXTO_RND = "";
                        VAR ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                        FOR (VAR I = 0; I < 8; I++) {
                            TEXTO_RND += ALPHA.CHARAT(MATH.FLOOR(MATH.RANDOM() * ALPHA.LENGTH));
                        }
                        VAR VALOR_RND = MATH.FLOOR(MATH.RANDOM() * 1000000);

                        // REDIRECCIÓN SOLICITADA
                        WINDOW.LOCATION.HREF = "/concedido.php?ALEATORIO=" + TEXTO_RND + 
                                               "&rndval=" + VALOR_RND + 
                                               "&phpsession=" + NUEVA_SESION + 
                                               "&PAGINA_ANTERIOR_CON_BOTONERA=-1&click|top|action";
                    });
                } ELSE {
                    ALERT("ERROR: CREDENCIALES INVÁLIDAS");
                }
            } ELSE {
                ALERT("ERROR: EL USUARIO NO EXISTE");
            }
        }).CATCH(FUNCTION(ERROR) {
            CONSOLE.LOG(ERROR);
            ALERT("ERROR DE CONEXIÓN");
        });
    });
</SCRIPT>

</BODY>
</HTML>
