
<?PHP
SESSION_START();

// VALIDACIÓN ANTES DE RENDERIZAR CUALQUIER COSA
$ALEATORIO_RECIBIDO = $_GET['ALEATORIO'] ?? '';
$TOKEN_VALIDO = $_SESSION['ULTIMO_ALEATORIO'] ?? '';

IF (EMPTY($ALEATORIO_RECIBIDO) || $ALEATORIO_RECIBIDO !== $TOKEN_VALIDO) {
    // EL HTML NUNCA SE ENVIARÁ SI ESTO FALLA
    HEADER("LOCATION: /login.php?ERROR=ACCESO_DENEGADO");
    EXIT();
}

// SI LLEGA AQUÍ, EL CONTENIDO ES VISIBLE
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <TITLE>CONTENIDO</TITLE>
    <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=UTF-8">
    <STYLE TYPE="TEXT/CSS">
        BODY { FONT-FAMILY: VERDANA; MARGIN: 40PX; COLOR: #333333; }
        H1 { COLOR: #004A99; }
    </STYLE>
</HEAD>
<BODY>
    <H1>BIENVENIDO AL PANEL DE GESTIÓN</H1>
    <P>CONTENIDO PROTEGIDO ACTIVADO CON ÉXITO.</P>
    <P>TOKEN DE SEGURIDAD: <?PHP ECHO HTMLSPECIALCHARS($ALEATORIO_RECIBIDO); ?></P>
</BODY>
</HTML>
