<?PHP
SESSION_START();

// VALIDACIÓN DE SEGURIDAD ABSOLUTA
$TOKEN_URL = $_GET['ALEATORIO'] ?? '';
$TOKEN_SESION = $_SESSION['TOKEN_IFRAME'] ?? '';

IF (EMPTY($TOKEN_URL) || $TOKEN_URL !== $TOKEN_SESION || !ISSET($_SESSION['PHPSESS_MOTOR'])) {
    // EL HTML NO SE ENVÍA SI NO HAY SESIÓN VÁLIDA
    EXIT(); 
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <STYLE TYPE="TEXT/CSS">
        BODY { FONT-FAMILY: VERDANA; BACKGROUND-COLOR: #222; COLOR: #FFF; MARGIN: 0; PADDING: 20PX; }
        A { COLOR: #00AAFF; TEXT-DECORATION: NONE; DISPLAY: BLOCK; MARGIN: 15PX 0; FONT-SIZE: 12PX; }
        A:HOVER { TEXT-DECORATION: UNDERLINE; }
    </STYLE>
</HEAD>
<BODY>
    <B>EMPRESARIO</B>
    <HR>
    <A HREF="contenidoPrincipal.php?ALEATORIO=<?PHP ECHO $TOKEN_URL; ?>" TARGET="CONTENIDO">DASHBOARD</A>
    <A HREF="/configuracion.php?ALEATORIO=<?PHP ECHO $TOKEN_URL; ?>" TARGET="CONTENIDO">AJUSTES</A>
    <BR>
    <A HREF="/logout.php" TARGET="_TOP" STYLE="COLOR:RED;">CERRAR SISTEMA</A>
</BODY>
</HTML>
