<?PHP
SESSION_START();

// VALIDACIÓN ANTES DE RENDERIZAR CUALQUIER COSA
$ALEATORIO_RECIBIDO = $_GET['ALEATORIO'] ?? '';
$TOKEN_VALIDO = $_SESSION['ULTIMO_ALEATORIO'] ?? '';

IF (EMPTY($ALEATORIO_RECIBIDO) || $ALEATORIO_RECIBIDO !== $TOKEN_VALIDO) {
    // SI NO HAY SESIÓN, REDIRIGIMOS AL LOGIN Y MATAMOS EL PROCESO
    HEADER("LOCATION: /login.php?ERROR=SESION_INVALIDA");
    EXIT(); 
}

// SI LLEGA AQUÍ, LA SESIÓN ES CORRECTA
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <TITLE>SIDEBAR</TITLE>
    <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=UTF-8">
    <STYLE TYPE="TEXT/CSS">
        BODY { FONT-FAMILY: VERDANA; BACKGROUND-COLOR: #333333; COLOR: #FFFFFF; MARGIN: 0; PADDING: 15PX; }
        A { COLOR: #CCCCCC; TEXT-DECORATION: NONE; FONT-SIZE: 12PX; DISPLAY: BLOCK; PADDING: 8PX; }
        A:HOVER { BACKGROUND-COLOR: #444444; COLOR: #FFFFFF; }
    </STYLE>
</HEAD>
<BODY>
    <B>MENU EMPRESARIO</B>
    <HR>
    <A HREF="contenidoPrincipal.php?ALEATORIO=<?PHP ECHO $ALEATORIO_RECIBIDO; ?>" TARGET="CONTENIDO">INICIO</A>
    <A HREF="/logout.php" TARGET="_TOP">SALIR</A>
</BODY>
</HTML>
